mail:
    host: smtp.gmail.com
    port: 587
    username: blubb@googlemail.com
    password: "dummy"
    protocol: smtp
    tls: true
    auth: true
    from: blubb@googlemail.com
    replyTo: blubb@googlemail.com
