server:
  port: 9999

spring:
    thymeleaf:
        check-template-location: false

mail:
    host: localhost
    port: 25
    username:
    password:
    protocol: smtp
    tls: false
    auth: false
    from: myMail@domain.com
    replyTo: myMail@domain.com